############## clock and reset define##################
create_clock -period 20.000 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN Y18 [get_ports sys_clk]

set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN F15 [get_ports rst_n]
############## HDMI_O###########################
set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_n]
set_property PACKAGE_PIN K4 [get_ports TMDS_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[0]}]
set_property PACKAGE_PIN V20 [get_ports {TMDS_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[1]}]
set_property PACKAGE_PIN T20 [get_ports {TMDS_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[2]}]
set_property PACKAGE_PIN M3 [get_ports {TMDS_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[2]}]
set_property PACKAGE_PIN V16 [get_ports hdmi_oen]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_oen[0]}]
########AN108 ON AX7020 and AX7010  J11##################
set_property PACKAGE_PIN D15 [get_ports ad9708_clk]
set_property PACKAGE_PIN C14 [get_ports {ad9708_data[7]}]
set_property PACKAGE_PIN C15 [get_ports {ad9708_data[6]}]
set_property PACKAGE_PIN G19 [get_ports {ad9708_data[5]}]
set_property PACKAGE_PIN B16 [get_ports {ad9708_data[4]}]
set_property PACKAGE_PIN J18  [get_ports {ad9708_data[3]}]
set_property PACKAGE_PIN C17 [get_ports {ad9708_data[2]}]
set_property PACKAGE_PIN E16 [get_ports {ad9708_data[1]}]
set_property PACKAGE_PIN L17  [get_ports {ad9280_data[0]}]
set_property PACKAGE_PIN A15 [get_ports {ad9280_data[1]}]
set_property PACKAGE_PIN A19 [get_ports {ad9280_data[2]}]
set_property PACKAGE_PIN A18 [get_ports {ad9280_data[3]}]
set_property PACKAGE_PIN F14 [get_ports {ad9280_data[4]}]
set_property PACKAGE_PIN F13 [get_ports {ad9280_data[5]}]
set_property PACKAGE_PIN E14 [get_ports {ad9280_data[6]}]
set_property PACKAGE_PIN E13 [get_ports {ad9280_data[7]}]
set_property PACKAGE_PIN B13 [get_ports ad9280_clk]

set_property IOSTANDARD LVCMOS33 [get_ports ad9708_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9708_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9708_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9708_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9708_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9708_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9708_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9708_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9708_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9280_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9280_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9280_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9280_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9280_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9280_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9280_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad9280_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports ad9280_clk]





set_property PACKAGE_PIN L3 [get_ports {TMDS_data_p[0]}]
set_property PACKAGE_PIN L5 [get_ports {TMDS_data_p[1]}]
set_property PACKAGE_PIN H5 [get_ports {hdmi_oen[0]}]
set_property PACKAGE_PIN D16 [get_ports {ad9708_data[0]}]
set_property PACKAGE_PIN D17 [get_ports {ad9708_data[3]}]
set_property PACKAGE_PIN B15 [get_ports {ad9708_data[5]}]
set_property PACKAGE_PIN A16 [get_ports {ad9280_data[0]}]

set_property PACKAGE_PIN G22 [get_ports {mode[0]}]
set_property PACKAGE_PIN D22 [get_ports {mode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[1]}]
