# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/BaiduNetDiskdownload/19_an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/sin_rom/sin_rom.xci
# IP: The module: 'sin_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/BaiduNetDiskdownload/19_an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/sin_rom/sin_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sin_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/BaiduNetDiskdownload/19_an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/sin_rom/sin_rom.xci
# IP: The module: 'sin_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/BaiduNetDiskdownload/19_an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/sin_rom/sin_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sin_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
