# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/BaiduNetDiskdownload/19_an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/saw_rom/saw_rom.xci
# IP: The module: 'saw_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/BaiduNetDiskdownload/19_an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/saw_rom/saw_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'saw_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/BaiduNetDiskdownload/19_an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/saw_rom/saw_rom.xci
# IP: The module: 'saw_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/BaiduNetDiskdownload/19_an108_adda_hdmi_test/an108_adda_lcd.srcs/sources_1/ip/saw_rom/saw_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'saw_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
